---
title: "Chronic Disease Indicator Analysis"
author: "Mel"
date: "2024-07-29"
output: html_document
---

```{r}
# reading in file/data

library(readr)

file <- "C:/Users/lissa/Downloads/U.S._Chronic_Disease_Indicators__CDI___2023_Release.csv"
data <- read.csv(file)

```

```{r}
# Load dplyr
library(tidyverse)
library(dplyr)

# Ggplot2

install.packages("ggplot2")
library(ggplot2)

# Janitor package helps with lots of naming fixes
library(janitor)
```

```{r}
# creating a tibble

tbl_data <- tibble(data)
```

```{r}
# Filtering data
fil_data <- filter(data, 
                   DataSource == "Death Certificate", 
                   StratificationCategory1 == "Gender",
                   Stratification1 == "Female",
                   Question == "Cancer of the female breast, mortality",
                   DataValueType == "Average Annual Age-adjusted Rate")

fil_data <- unite(fil_data, YearStart, YearEnd, sep = "-", col = "Years", remove = TRUE)

group_by(fil_data, LocationDesc, .add = TRUE)

```

```{r}
pull(fil_data, "Years") %>% table()

fil_data <- filter(fil_data,
                   Years == "2015-2019")
```

```{r}
# Graphing data

plt1 <- ggplot(data = fil_data, mapping = aes(x = Years, 
                                              y = DataValue)) +
geom_bar()
theme(legend.position = "bottom")

```



